version: "3.7"

services:
  proxy:
    # The official v2.0 Traefik docker image
    image: traefik
    container_name: "traefik"
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.file=true
      - --providers.file.directory=/etc/traefik/dynamic
      - --log.level=DEBUG
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # File provider
      - ${PWD}/traefik.yaml:/etc/traefik/dynamic/traefik.yaml
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    container_name: "whoami"
    labels:
      - "traefik.http.routers.whoami.rule=Path(`/whoami`)"
  webapp-host:
    image: containous/whoami
    container_name: "webapp"
    ports:
      - "5001:80"
    labels:
      - "traefik.enable=false" # Disable auto-discovery: rely on file provider instead

